version: '3'
services:
  infra:
    build: ./infra
    ports:
      - "8080:8080"
    depends_on:
      - "db"
  db:
    image: "postgres"
    restart: always
    ports:
         - 5432:5432
    volumes:
    - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    - ./migrations/food.csv:/var/lib/postgresql/food.csv
    - ./migrations/branded_food.csv:/var/lib/postgresql/branded_food.csv
    - ./migrations/food_nutrient.csv:/var/lib/postgresql/food_nutrient.csv
    - ./migrations/nutrient.csv:/var/lib/postgresql/nutrient.csv
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db