version: '3'
services:
  infra:
    build: ./infra
    ports:
      - "8080:8080"
    depends_on:
      - "db"
  db:
    image: "postgres"
    restart: always
    ports:
         - 5432:5432
    volumes:
    - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db