version: '3'
services:
  infra:
    build: ./infra
    ports:
      - "8080:8080"
  db:
    image: "postgres"
    ports:
         - 5432:5432
    volumes:
    - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql