version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers
  
    working_directory: ~/repo
    steps:
        - checkout
        
        - run: yarn install
        - run: yarn test
  test:
    docker:
      - image: golang:latest
    steps:
      - checkout
      - run: echo "test"
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run: apt -y install nodejs
      - run: apt -y install yarn
      - run: curl -o- -L https://yarnpkg.com/install.sh | bash
      - checkout
      - run: cd app; yarn install
      - run: make deploy.app
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - deploy