version: 2.1
  jobs:
    push_app:
      docker:
        - image: node:latest
    push_infra:
      docker:
        - image: golang:1.12.10
workflows:
  version: 2
  jobs:
    jobs:
      - push_app
      - push_infra